### ISSUE TITLE
Support for Harbor

### ISSUE THREAD

**Issue by Chaosflo** [dotnet/sdk-container-builds#418]
Hey folks! 
I really like the work you have done here, I tried to use this with combination of habor. 

https://github.com/goharbor/harbor

But it doesn't really work sadly, the api calls seem to be off and authorization seems to be broken too. 
I have done the authorization via environment variables to test if it works at all (found them in source code)

This is the api error 
/opt/azure_repos/home_dir_tgw_user/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Failed to push to the output registry: System.ApplicationException: CONTAINER1001: Failed to upload blob to POST****

**Comment by baronfel** [comment]
I dug into this a bit on my demo repo: https://github.com/baronfel/sdk-container-demo/actions/runs/4755870576/jobs/8450631677

After some searching (and thanks to the error dump) it seems that Harbor is sending a session token and CSRF token. It appears that their server implementation does CSRF validation even on these endpoints if session information is provided. Based on the Docker API conformance changes [here](https://github.com/opencontainers/distribution-spec/pull/144) I think we need to update our use of HTTPClient to not automatically handle 'Set-Cookie' headers on responses.

**Comment by autotmp** [comment]
Is this possibly affecting other registries? I'm currently having issues pushing to our GitLab registries via `dotnet publish`. Failures are consistent in CI and locally. Using `docker push` directly works as expected.  Error output below

```bash
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Failed to push to the output registry: System.ApplicationException: CONTAINER1001: Failed to upload blob to POST https://registry.gitlab.com/v2/my-user/sandbox/dotnet-container-app/blobs/uploads/; received Unauthorized with detail Docker-Distribution-Api-Version: registry/2.0 [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: WWW-Authenticate: Bearer realm="https://gitlab.com/jwt/auth",service="container_registry",scope="repository:my-user/sandbox/dotnet-container-app:pull,push",error="insufficient_scope" [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: X-Content-Type-Options: nosniff [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Date: Tue, 09 May 2023 13:34:35 GMT [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:  [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
/Users/dev/.nuget/packages/microsoft.net.build.containers/0.4.0/build/Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"my-user/sandbox/dotnet-container-app","Action":"pull"},{"Type":"repository","Class":"","Name":"my-user/sandbox/dotnet-container-app","Action":"push"}]}]} [/Users/dev/git/gitlab/dotnet-container-app/src/Worker1/DotNet.ContainerImage1.csproj]
....
```

Or this issue with GitLab solved by https://github.com/dotnet/sdk/pull/32301?

**Comment by Pyroluk** [comment]
I am experiencing the same issue with the [official docker registry 2.0 image](https://hub.docker.com/_/registry) using basic authentication (username and password):

`2>Failed to push to the output registry: CONTAINER1001: Failed to upload blob to POST https://XXX.XXX:50000/v2/XXX/blobs/uploads/; received Unauthorized with detail Docker-Distribution-Api-Version: registry/2.0`

**Comment by baronfel** [comment]
@Pyroluk can you look at https://github.com/dotnet/sdk-container-builds/issues/314 and see if that matches your problem? We don't have a fix for it yet.

**Comment by Pyroluk** [comment]
@baronfel Yes, same problem. Thank you for pointing me to the issue.

**Comment by djheap** [comment]
Pushing images to Harbor is an important scenario for us as well and it still appears to be broken. I tried the latest dotnet 8 daily .20x sdk build and still received 'Forbidden' status code failures. From detailed logs I can see:

**Response content: {"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}**

The newer demo repo seems to indicate that it has been fixed, however (https://github.com/baronfel/sdk-container-demo/actions/runs/5172500858). Are there fixes not yet included in the daily SDK builds?

**Comment by djheap** [comment]
Is there an issue for that we can track? I haven't found one that seems to be it.

**Comment by baronfel** [comment]
@djheap can you try this package and see if that addresses the cookie issue?

[Microsoft.NET.Build.Containers.8.0.200-dev.nupkg.zip](https://github.com/dotnet/sdk-container-builds/files/13503748/Microsoft.NET.Build.Containers.8.0.200-dev.nupkg.zip)

**Comment by djheap** [comment]
Yes, that worked well, thank you - we are looking forward to significantly simplifying our pipelines!

**Comment by baronfel** [comment]
Great to hear!

**Comment by baronfel** [comment]
Closing as it's resolved :)
